backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: cds-snc/c-19-benefits-cms
  base_url: https://f1jj4za18c.execute-api.us-east-1.amazonaws.com
  auth_endpoint: /production/auth

# when using the default proxy server port
# local_backend: true

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow

collections:
  # Our pages e.g. Home, Contact
  - name: "enPages"
    label: "Page - EN"
    folder: "en/pages"
    create: true # Change to true to allow editors to create new pages
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Intro", name: "intro", widget: "markdown", hint: "This text comes before the pages Table of Contents. Leave blank if you want the Table of Contents to appear first" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "frPages"
    label: "Page - FR"
    folder: "en/pages"
    create: true # Change to true to allow editors to create new pages
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Intro", name: "intro", widget: "markdown", hint: "This text comes before the pages Table of Contents. Leave blank if you want the Table of Contents first" }
      - { label: "Body", name: "body", widget: "markdown" }
