backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our pages e.g. Home, Contact
  - name: "enPages"
    label: "Page - EN"
    folder: "en/pages"
    create: true # Change to true to allow editors to create new pages
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Intro", name: "intro", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "frPages"
    label: "Page - FR"
    folder: "en/pages"
    create: true # Change to true to allow editors to create new pages
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Intro", name: "intro", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
