name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.5.0'
      - name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy Bilingual
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: _site
          container_name: $web
          connection_string: ${{ secrets.AZ_ConnectionString }}
      - name: Deploy English
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: _site/en
          container_name: $web
          connection_string: ${{ secrets.AZ_EN_ConnectionString }}
      - name: Deploy French
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: _site/fr
          container_name: $web
          connection_string: ${{ secrets.AZ_FR_ConnectionString }}